# collect_dataset.yaml
defaults:
  - _self_  # Fix for the Hydra warning

# Your configuration values
data_paths:
  vlmaps_data_dir: "/vlmaps/drive/"
  habitat_scene_dir: "/vlmaps/tasks/hm3d"  # Use absolute paths here too

scene_names:
  - #kfPV7w3FaU5
data_cfg:
  rgb: true
  depth: true
  semantic: true
  resolution:
    w: 1080
    h: 720
  camera_height: 1.5
